name: 🌆 Generate GitHub Skyline

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  skyline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 🌃 Generate skyline SVGs
        uses: github-actions-contrib/skyline@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: 💾 Commit skyline
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "🌆 Update GitHub skyline" || exit 0
          git push
